- name: Deploy to EC2 via SSH
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |

      echo "Logging into AWS ECR..."

      aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
      | docker login --username AWS \
        --password-stdin 216989134640.dkr.ecr.eu-north-1.amazonaws.com

      echo "Pulling latest image..."

      docker pull 216989134640.dkr.ecr.eu-north-1.amazonaws.com/taskapp:latest

      echo "Stopping old container..."

      docker stop taskapp-container || true
      docker rm taskapp-container || true

      echo "Running new container..."

      docker run -d -p 3000:3000 \
        --name taskapp-container \
        216989134640.dkr.ecr.eu-north-1.amazonaws.com/taskapp:latest
